/**
 * Bundled country dataset — used as offline fallback / primary source
 * since restcountries.com v3.1 was deprecated and v5 requires an API key.
 *
 * 30 representative countries covering all continents.
 * Flag images served from flagcdn.com (free CDN, no auth, HTTPS).
 *
 * Schema kept compatible with restcountries.com v3.1 response shape so
 * the frontend stays schema-stable if we ever switch back to a live API.
 */

export interface Country {
  name: { common: string; official: string };
  flags: { png: string; alt: string };
  capital: string[];
  population: number;
  languages: Record<string, string>;
  region: string;
  maps: { googleMaps: string };
}

const flag = (code: string, name: string) => ({
  png: `https://flagcdn.com/w320/${code}.png`,
  alt: `${name} 国旗`,
});

const c = (
  common: string,
  official: string,
  code: string,
  capital: string[],
  population: number,
  languages: Record<string, string>,
  region: string,
  googleMaps: string,
): Country => ({
  name: { common, official },
  flags: flag(code, common),
  capital,
  population,
  languages,
  region,
  maps: { googleMaps },
});

export const BUNDLED_COUNTRIES: Country[] = [
  c(
    '中国',
    '中华人民共和国',
    'cn',
    ['北京'],
    1_411_000_000,
    { zho: '汉语' },
    'Asia',
    'https://www.google.com/maps/place/China',
  ),
  c(
    '美国',
    '美利坚合众国',
    'us',
    ['华盛顿'],
    331_000_000,
    { eng: '英语' },
    'Americas',
    'https://www.google.com/maps/place/USA',
  ),
  c(
    '日本',
    '日本国',
    'jp',
    ['东京'],
    125_000_000,
    { jpn: '日语' },
    'Asia',
    'https://www.google.com/maps/place/Japan',
  ),
  c(
    '韩国',
    '大韩民国',
    'kr',
    ['首尔'],
    51_000_000,
    { kor: '韩语' },
    'Asia',
    'https://www.google.com/maps/place/South+Korea',
  ),
  c(
    '印度',
    '印度共和国',
    'in',
    ['新德里'],
    1_380_000_000,
    { hin: '印地语', eng: '英语' },
    'Asia',
    'https://www.google.com/maps/place/India',
  ),
  c(
    '英国',
    '大不列颠及北爱尔兰联合王国',
    'gb',
    ['伦敦'],
    67_000_000,
    { eng: '英语' },
    'Europe',
    'https://www.google.com/maps/place/UK',
  ),
  c(
    '法国',
    '法兰西共和国',
    'fr',
    ['巴黎'],
    65_000_000,
    { fra: '法语' },
    'Europe',
    'https://www.google.com/maps/place/France',
  ),
  c(
    '德国',
    '德意志联邦共和国',
    'de',
    ['柏林'],
    83_000_000,
    { deu: '德语' },
    'Europe',
    'https://www.google.com/maps/place/Germany',
  ),
  c(
    '意大利',
    '意大利共和国',
    'it',
    ['罗马'],
    60_000_000,
    { ita: '意大利语' },
    'Europe',
    'https://www.google.com/maps/place/Italy',
  ),
  c(
    '西班牙',
    '西班牙王国',
    'es',
    ['马德里'],
    47_000_000,
    { spa: '西班牙语' },
    'Europe',
    'https://www.google.com/maps/place/Spain',
  ),
  c(
    '俄罗斯',
    '俄罗斯联邦',
    'ru',
    ['莫斯科'],
    144_000_000,
    { rus: '俄语' },
    'Europe',
    'https://www.google.com/maps/place/Russia',
  ),
  c(
    '加拿大',
    '加拿大',
    'ca',
    ['渥太华'],
    38_000_000,
    { eng: '英语', fra: '法语' },
    'Americas',
    'https://www.google.com/maps/place/Canada',
  ),
  c(
    '巴西',
    '巴西联邦共和国',
    'br',
    ['巴西利亚'],
    212_000_000,
    { por: '葡萄牙语' },
    'Americas',
    'https://www.google.com/maps/place/Brazil',
  ),
  c(
    '墨西哥',
    '墨西哥合众国',
    'mx',
    ['墨西哥城'],
    126_000_000,
    { spa: '西班牙语' },
    'Americas',
    'https://www.google.com/maps/place/Mexico',
  ),
  c(
    '阿根廷',
    '阿根廷共和国',
    'ar',
    ['布宜诺斯艾利斯'],
    45_000_000,
    { spa: '西班牙语' },
    'Americas',
    'https://www.google.com/maps/place/Argentina',
  ),
  c(
    '澳大利亚',
    '澳大利亚联邦',
    'au',
    ['堪培拉'],
    25_000_000,
    { eng: '英语' },
    'Oceania',
    'https://www.google.com/maps/place/Australia',
  ),
  c(
    '新西兰',
    '新西兰',
    'nz',
    ['惠灵顿'],
    5_000_000,
    { eng: '英语', mri: '毛利语' },
    'Oceania',
    'https://www.google.com/maps/place/New+Zealand',
  ),
  c(
    '埃及',
    '阿拉伯埃及共和国',
    'eg',
    ['开罗'],
    102_000_000,
    { ara: '阿拉伯语' },
    'Africa',
    'https://www.google.com/maps/place/Egypt',
  ),
  c(
    '南非',
    '南非共和国',
    'za',
    ['比勒陀利亚'],
    59_000_000,
    { eng: '英语', afr: '南非荷兰语' },
    'Africa',
    'https://www.google.com/maps/place/South+Africa',
  ),
  c(
    '肯尼亚',
    '肯尼亚共和国',
    'ke',
    ['内罗毕'],
    54_000_000,
    { eng: '英语', swa: '斯瓦希里语' },
    'Africa',
    'https://www.google.com/maps/place/Kenya',
  ),
  c(
    '尼日利亚',
    '尼日利亚联邦共和国',
    'ng',
    ['阿布贾'],
    206_000_000,
    { eng: '英语' },
    'Africa',
    'https://www.google.com/maps/place/Nigeria',
  ),
  c(
    '土耳其',
    '土耳其共和国',
    'tr',
    ['安卡拉'],
    84_000_000,
    { tur: '土耳其语' },
    'Asia',
    'https://www.google.com/maps/place/Turkey',
  ),
  c(
    '沙特阿拉伯',
    '沙特阿拉伯王国',
    'sa',
    ['利雅得'],
    34_000_000,
    { ara: '阿拉伯语' },
    'Asia',
    'https://www.google.com/maps/place/Saudi+Arabia',
  ),
  c(
    '阿联酋',
    '阿拉伯联合酋长国',
    'ae',
    ['阿布扎比'],
    9_000_000,
    { ara: '阿拉伯语' },
    'Asia',
    'https://www.google.com/maps/place/UAE',
  ),
  c(
    '泰国',
    '泰王国',
    'th',
    ['曼谷'],
    69_000_000,
    { tha: '泰语' },
    'Asia',
    'https://www.google.com/maps/place/Thailand',
  ),
  c(
    '越南',
    '越南社会主义共和国',
    'vn',
    ['河内'],
    97_000_000,
    { vie: '越南语' },
    'Asia',
    'https://www.google.com/maps/place/Vietnam',
  ),
  c(
    '印度尼西亚',
    '印度尼西亚共和国',
    'id',
    ['雅加达'],
    273_000_000,
    { ind: '印尼语' },
    'Asia',
    'https://www.google.com/maps/place/Indonesia',
  ),
  c(
    '菲律宾',
    '菲律宾共和国',
    'ph',
    ['马尼拉'],
    109_000_000,
    { eng: '英语', fil: '菲律宾语' },
    'Asia',
    'https://www.google.com/maps/place/Philippines',
  ),
  c(
    '新加坡',
    '新加坡共和国',
    'sg',
    ['新加坡'],
    5_700_000,
    { eng: '英语', zho: '汉语', msa: '马来语', tam: '泰米尔语' },
    'Asia',
    'https://www.google.com/maps/place/Singapore',
  ),
  c(
    '瑞士',
    '瑞士联邦',
    'ch',
    ['伯尔尼'],
    8_600_000,
    { deu: '德语', fra: '法语', ita: '意大利语' },
    'Europe',
    'https://www.google.com/maps/place/Switzerland',
  ),
];
