/**
 * Bundled fruit dataset — 49 fruits from Fruityvice API.
 * Pre-processed with Chinese names (nameZh).
 * Served locally to avoid external API dependency.
 */
export const FRUITS_SEED_DATA = [
  {
    name: 'Persimmon',
    nameZh: '柿子',
    family: 'Ebenaceae',
    genus: 'Diospyros',
    order: 'Rosales',
    nutritions: {
      calories: 81,
      fat: 0,
      sugar: 18,
      carbohydrates: 18,
      protein: 0,
    },
    id: 52,
  },
  {
    name: 'Strawberry',
    nameZh: '草莓',
    family: 'Rosaceae',
    genus: 'Fragaria',
    order: 'Rosales',
    nutritions: {
      calories: 29,
      fat: 0.4,
      sugar: 5.4,
      carbohydrates: 5.5,
      protein: 0.8,
    },
    id: 3,
  },
  {
    name: 'Banana',
    nameZh: '香蕉',
    family: 'Musaceae',
    genus: 'Musa',
    order: 'Zingiberales',
    nutritions: {
      calories: 96,
      fat: 0.2,
      sugar: 17.2,
      carbohydrates: 22,
      protein: 1,
    },
    id: 1,
  },
  {
    name: 'Tomato',
    nameZh: '番茄',
    family: 'Solanaceae',
    genus: 'Solanum',
    order: 'Solanales',
    nutritions: {
      calories: 74,
      fat: 0.2,
      sugar: 2.6,
      carbohydrates: 3.9,
      protein: 0.9,
    },
    id: 5,
  },
  {
    name: 'Pear',
    nameZh: '梨',
    family: 'Rosaceae',
    genus: 'Pyrus',
    order: 'Rosales',
    nutritions: {
      calories: 57,
      fat: 0.1,
      sugar: 10,
      carbohydrates: 15,
      protein: 0.4,
    },
    id: 4,
  },
  {
    name: 'Durian',
    nameZh: '榴莲',
    family: 'Malvaceae',
    genus: 'Durio',
    order: 'Malvales',
    nutritions: {
      calories: 147,
      fat: 5.3,
      sugar: 6.75,
      carbohydrates: 27.1,
      protein: 1.5,
    },
    id: 60,
  },
  {
    name: 'Blackberry',
    nameZh: '黑莓',
    family: 'Rosaceae',
    genus: 'Rubus',
    order: 'Rosales',
    nutritions: {
      calories: 40,
      fat: 0.4,
      sugar: 4.5,
      carbohydrates: 9,
      protein: 1.3,
    },
    id: 64,
  },
  {
    name: 'Lingonberry',
    nameZh: '越橘',
    family: 'Ericaceae',
    genus: 'Vaccinium',
    order: 'Ericales',
    nutritions: {
      calories: 50,
      fat: 0.34,
      sugar: 5.74,
      carbohydrates: 11.3,
      protein: 0.75,
    },
    id: 65,
  },
  {
    name: 'Kiwi',
    nameZh: '猕猴桃',
    family: 'Actinidiaceae',
    genus: 'Apteryx',
    order: 'Struthioniformes',
    nutritions: {
      calories: 61,
      fat: 0.5,
      sugar: 9,
      carbohydrates: 15,
      protein: 1.1,
    },
    id: 66,
  },
  {
    name: 'Lychee',
    nameZh: '荔枝',
    family: 'Sapindaceae',
    genus: 'Litchi',
    order: 'Sapindales',
    nutritions: {
      calories: 66,
      fat: 0.44,
      sugar: 15,
      carbohydrates: 17,
      protein: 0.8,
    },
    id: 67,
  },
  {
    name: 'Pineapple',
    nameZh: '菠萝',
    family: 'Bromeliaceae',
    genus: 'Ananas',
    order: 'Poales',
    nutritions: {
      calories: 50,
      fat: 0.12,
      sugar: 9.85,
      carbohydrates: 13.12,
      protein: 0.54,
    },
    id: 10,
  },
  {
    name: 'Fig',
    nameZh: '无花果',
    family: 'Moraceae',
    genus: 'Ficus',
    order: 'Rosales',
    nutritions: {
      calories: 74,
      fat: 0.3,
      sugar: 16,
      carbohydrates: 19,
      protein: 0.8,
    },
    id: 68,
  },
  {
    name: 'Gooseberry',
    nameZh: '鹅莓',
    family: 'Grossulariaceae',
    genus: 'Ribes',
    order: 'Saxifragales',
    nutritions: {
      calories: 44,
      fat: 0.6,
      sugar: 0,
      carbohydrates: 10,
      protein: 0.9,
    },
    id: 69,
  },
  {
    name: 'Passionfruit',
    nameZh: '百香果',
    family: 'Passifloraceae',
    genus: 'Passiflora',
    order: 'Malpighiales',
    nutritions: {
      calories: 97,
      fat: 0.7,
      sugar: 11.2,
      carbohydrates: 22.4,
      protein: 2.2,
    },
    id: 70,
  },
  {
    name: 'Plum',
    nameZh: '李子',
    family: 'Rosaceae',
    genus: 'Prunus',
    order: 'Rosales',
    nutritions: {
      calories: 46,
      fat: 0.28,
      sugar: 9.92,
      carbohydrates: 11.4,
      protein: 0.7,
    },
    id: 71,
  },
  {
    name: 'Orange',
    nameZh: '橙子',
    family: 'Rutaceae',
    genus: 'Citrus',
    order: 'Sapindales',
    nutritions: {
      calories: 43,
      fat: 0.2,
      sugar: 8.2,
      carbohydrates: 8.3,
      protein: 1,
    },
    id: 2,
  },
  {
    name: 'GreenApple',
    nameZh: '苹果',
    family: 'Rosaceae',
    genus: 'Malus',
    order: 'Rosales',
    nutritions: {
      calories: 21,
      fat: 0.1,
      sugar: 6.4,
      carbohydrates: 3.1,
      protein: 0.4,
    },
    id: 72,
  },
  {
    name: 'Raspberry',
    nameZh: '树莓',
    family: 'Rosaceae',
    genus: 'Rubus',
    order: 'Rosales',
    nutritions: {
      calories: 53,
      fat: 0.7,
      sugar: 4.4,
      carbohydrates: 12,
      protein: 1.2,
    },
    id: 23,
  },
  {
    name: 'Watermelon',
    nameZh: '西瓜',
    family: 'Cucurbitaceae',
    genus: 'Citrullus',
    order: 'Cucurbitales',
    nutritions: {
      calories: 30,
      fat: 0.2,
      sugar: 6,
      carbohydrates: 8,
      protein: 0.6,
    },
    id: 25,
  },
  {
    name: 'Lemon',
    nameZh: '柠檬',
    family: 'Rutaceae',
    genus: 'Citrus',
    order: 'Sapindales',
    nutritions: {
      calories: 29,
      fat: 0.3,
      sugar: 2.5,
      carbohydrates: 9,
      protein: 1.1,
    },
    id: 26,
  },
  {
    name: 'Mango',
    nameZh: '芒果',
    family: 'Anacardiaceae',
    genus: 'Mangifera',
    order: 'Sapindales',
    nutritions: {
      calories: 60,
      fat: 0.38,
      sugar: 13.7,
      carbohydrates: 15,
      protein: 0.82,
    },
    id: 27,
  },
  {
    name: 'Blueberry',
    nameZh: '蓝莓',
    family: 'Rosaceae',
    genus: 'Fragaria',
    order: 'Rosales',
    nutritions: {
      calories: 29,
      fat: 0.4,
      sugar: 5.4,
      carbohydrates: 5.5,
      protein: 0,
    },
    id: 33,
  },
  {
    name: 'Apple',
    nameZh: '苹果',
    family: 'Rosaceae',
    genus: 'Malus',
    order: 'Rosales',
    nutritions: {
      calories: 52,
      fat: 0.4,
      sugar: 10.3,
      carbohydrates: 11.4,
      protein: 0.3,
    },
    id: 6,
  },
  {
    name: 'Guava',
    nameZh: '番石榴',
    family: 'Myrtaceae',
    genus: 'Psidium',
    order: 'Myrtales',
    nutritions: {
      calories: 68,
      fat: 1,
      sugar: 9,
      carbohydrates: 14,
      protein: 2.6,
    },
    id: 37,
  },
  {
    name: 'Apricot',
    nameZh: '杏',
    family: 'Rosaceae',
    genus: 'Prunus',
    order: 'Rosales',
    nutritions: {
      calories: 15,
      fat: 0.1,
      sugar: 3.2,
      carbohydrates: 3.9,
      protein: 0.5,
    },
    id: 35,
  },
  {
    name: 'Melon',
    nameZh: '甜瓜',
    family: 'Cucurbitaceae',
    genus: 'Cucumis',
    order: 'Cucurbitaceae',
    nutritions: {
      calories: 34,
      fat: 0,
      sugar: 8,
      carbohydrates: 8,
      protein: 0,
    },
    id: 41,
  },
  {
    name: 'Tangerine',
    nameZh: '橘子',
    family: 'Rutaceae',
    genus: 'Citrus',
    order: 'Sapindales',
    nutritions: {
      calories: 45,
      fat: 0.4,
      sugar: 9.1,
      carbohydrates: 8.3,
      protein: 0,
    },
    id: 77,
  },
  {
    name: 'Pitahaya',
    nameZh: '火龙果',
    family: 'Cactaceae',
    genus: 'Cactaceae',
    order: 'Caryophyllales',
    nutritions: {
      calories: 36,
      fat: 0.4,
      sugar: 3,
      carbohydrates: 7,
      protein: 1,
    },
    id: 78,
  },
  {
    name: 'Lime',
    nameZh: '青柠',
    family: 'Rutaceae',
    genus: 'Citrus',
    order: 'Sapindales',
    nutritions: {
      calories: 25,
      fat: 0.1,
      sugar: 1.7,
      carbohydrates: 8.4,
      protein: 0.3,
    },
    id: 44,
  },
  {
    name: 'Pomegranate',
    nameZh: '石榴',
    family: 'Lythraceae',
    genus: 'Punica',
    order: 'Myrtales',
    nutritions: {
      calories: 83,
      fat: 1.2,
      sugar: 13.7,
      carbohydrates: 18.7,
      protein: 1.7,
    },
    id: 79,
  },
  {
    name: 'Dragonfruit',
    nameZh: '火龙果',
    family: 'Cactaceae',
    genus: 'Selenicereus',
    order: 'Caryophyllales',
    nutritions: {
      calories: 60,
      fat: 1.5,
      sugar: 8,
      carbohydrates: 9,
      protein: 9,
    },
    id: 80,
  },
  {
    name: 'Grape',
    nameZh: '葡萄',
    family: 'Vitaceae',
    genus: 'Vitis',
    order: 'Vitales',
    nutritions: {
      calories: 69,
      fat: 0.16,
      sugar: 16,
      carbohydrates: 18.1,
      protein: 0.72,
    },
    id: 81,
  },
  {
    name: 'Morus',
    nameZh: '桑葚',
    family: 'Moraceae',
    genus: 'Morus',
    order: 'Rosales',
    nutritions: {
      calories: 43,
      fat: 0.39,
      sugar: 8.1,
      carbohydrates: 9.8,
      protein: 1.44,
    },
    id: 82,
  },
  {
    name: 'Feijoa',
    nameZh: '斐济果',
    family: 'Myrtaceae',
    genus: 'Sellowiana',
    order: 'Myrtoideae',
    nutritions: {
      calories: 44,
      fat: 0.4,
      sugar: 3,
      carbohydrates: 8,
      protein: 0.6,
    },
    id: 76,
  },
  {
    name: 'Avocado',
    nameZh: '牛油果',
    family: 'Lauraceae',
    genus: 'Persea',
    order: 'Laurales',
    nutritions: {
      calories: 160,
      fat: 14.66,
      sugar: 0.66,
      carbohydrates: 8.53,
      protein: 2,
    },
    id: 84,
  },
  {
    name: 'Kiwifruit',
    nameZh: '猕猴桃',
    family: 'Actinidiaceae',
    genus: 'Actinidia',
    order: 'Ericales',
    nutritions: {
      calories: 61,
      fat: 0.5,
      sugar: 8.9,
      carbohydrates: 14.6,
      protein: 1.14,
    },
    id: 85,
  },
  {
    name: 'Cranberry',
    nameZh: '蔓越莓',
    family: 'Ericaceae',
    genus: 'Vaccinium',
    order: 'Ericales',
    nutritions: {
      calories: 46,
      fat: 0.1,
      sugar: 4,
      carbohydrates: 12.2,
      protein: 0.4,
    },
    id: 87,
  },
  {
    name: 'Cherry',
    nameZh: '樱桃',
    family: 'Rosaceae',
    genus: 'Prunus',
    order: 'Rosales',
    nutritions: {
      calories: 50,
      fat: 0.3,
      sugar: 8,
      carbohydrates: 12,
      protein: 1,
    },
    id: 9,
  },
  {
    name: 'Peach',
    nameZh: '桃子',
    family: 'Rosaceae',
    genus: 'Prunus',
    order: 'Rosales',
    nutritions: {
      calories: 39,
      fat: 0.25,
      sugar: 8.4,
      carbohydrates: 9.5,
      protein: 0.9,
    },
    id: 86,
  },
  {
    name: 'Jackfruit',
    nameZh: '菠萝蜜',
    family: 'Moraceae',
    genus: 'Artocarpus',
    order: 'Rosales',
    nutritions: {
      calories: 95,
      fat: 0,
      sugar: 19.1,
      carbohydrates: 23.2,
      protein: 1.72,
    },
    id: 94,
  },
  {
    name: 'Horned Melon',
    nameZh: '刺角瓜',
    family: 'Cucurbitaceae',
    genus: 'Cucumis',
    order: 'Cucurbitales',
    nutritions: {
      calories: 44,
      fat: 1.26,
      sugar: 0.5,
      carbohydrates: 7.56,
      protein: 1.78,
    },
    id: 95,
  },
  {
    name: 'Hazelnut',
    nameZh: '榛子',
    family: 'Betulaceae',
    genus: 'Corylus',
    order: 'Fagales',
    nutritions: {
      calories: 628,
      fat: 61,
      sugar: 4.3,
      carbohydrates: 17,
      protein: 15,
    },
    id: 96,
  },
  {
    name: 'Pomelo',
    nameZh: '柚子',
    family: 'Rutaceae',
    genus: 'Citrus',
    order: 'Sapindales',
    nutritions: {
      calories: 37,
      fat: 0,
      sugar: 8.5,
      carbohydrates: 9.67,
      protein: 0.82,
    },
    id: 98,
  },
  {
    name: 'Mangosteen',
    nameZh: '山竹',
    family: 'Clusiaceae',
    genus: 'Garcinia',
    order: 'Malpighiales',
    nutritions: {
      calories: 73,
      fat: 0.58,
      sugar: 16.11,
      carbohydrates: 17.91,
      protein: 0.41,
    },
    id: 99,
  },
  {
    name: 'Pumpkin',
    nameZh: '南瓜',
    family: 'Cucurbitaceae',
    genus: 'Cucurbita',
    order: 'Cucurbitales',
    nutritions: {
      calories: 25,
      fat: 0.3,
      sugar: 3.3,
      carbohydrates: 4.6,
      protein: 1.1,
    },
    id: 100,
  },
  {
    name: 'Japanese Persimmon',
    nameZh: '日本柿子',
    family: ' Ebenaceae',
    genus: 'Diospyros',
    order: ' Ericales',
    nutritions: {
      calories: 70,
      fat: 0.2,
      sugar: 13,
      carbohydrates: 19,
      protein: 0.6,
    },
    id: 101,
  },
  {
    name: 'Papaya',
    nameZh: '木瓜',
    family: 'Caricaceae',
    genus: 'Carica',
    order: 'Brassicales',
    nutritions: {
      calories: 39,
      fat: 0.3,
      sugar: 4.4,
      carbohydrates: 5.8,
      protein: 0.5,
    },
    id: 42,
  },
  {
    name: 'Annona',
    nameZh: '番荔枝',
    family: 'Annonaceae',
    genus: 'Annonas',
    order: 'Rosales',
    nutritions: {
      calories: 92,
      fat: 0.29,
      sugar: 3.4,
      carbohydrates: 19.1,
      protein: 1.5,
    },
    id: 103,
  },
  {
    name: 'Ceylon Gooseberry',
    nameZh: '鹅莓',
    family: 'Salicaceae',
    genus: 'Dovyalis',
    order: 'Malpighiales',
    nutritions: {
      calories: 47,
      fat: 0.3,
      sugar: 8.1,
      carbohydrates: 9.6,
      protein: 1.2,
    },
    id: 104,
  },
] as const;
